name = "GrIS1980s_DEM"
uuid = "33c15a80-d7e1-495f-a237-10f5cbc5c5cf"
version = "0.1.0"
authors = ["annegret <annegret.pohle@outlook.com>"]

[deps]
AbstractGPs = "99985d1d-32ba-4be9-9821-2ec096f28918"
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Cascadia = "54eefc05-d75b-58de-a785-1a3403f0919f"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
GeoDataFrames = "62cb38b5-d8d2-4862-a48e-6a340996859f"
GeoFormatTypes = "68eda718-8dee-11e9-39e7-89f7f65f511f"
GeoStats = "dcc97b0b-8ce5-5539-9008-bb190f959ef6"
GeometryOps = "3251bfac-6a57-4b6d-aa61-ac1fef2975ab"
Geomorphometry = "714e3e49-7933-471a-9334-4a6a65a92f36"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
Gumbo = "708ec375-b3d6-5a57-a7ce-8257bf98657a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
ImageMorphology = "787d08f9-d448-5407-9aad-5290dd7ab264"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LocalFilters = "085fde7c-5f94-55e4-8448-8bbb5db6dde9"
Measures = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
NetCDF = "30363a11-5582-574a-97bb-aa9a979735b9"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Shapefile = "8e980c4a-a4fe-5da2-b3a7-4b4b0353a2f4"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

[compat]
AbstractGPs = "0.5.24"
ArchGDAL = "0.10.4"
ArgParse = "1.2.0"
Arpack = "0.5.4"
CSV = "0.10.15"
Cascadia = "1.0.2"
Colors = "0.13.1"
DataFrames = "1.7.0"
DataStructures = "0.18.20"
DelimitedFiles = "1.9.1"
Distances = "0.10.12"
Distributions = "0.25"
Downloads = "1.6.0"
GeoDataFrames = "0.3.12"
GeoFormatTypes = "0.4.2"
GeoStats = "0.68.4"
GeometryOps = "0.1.31"
Geomorphometry = "0.7.1"
Glob = "1.3.1"
Gumbo = "0.8.2"
HTTP = "1.10.9"
ImageFiltering = "0.7.8"
ImageMorphology = "0.4.5"
Interpolations = "0.15.1"
JLD2 = "0.4.53"
LaTeXStrings = "1.4.0"
LocalFilters = "1.2.2"
Meshes = "0.51.22"
NCDatasets = "0.14.6"
NetCDF = "0.12.0"
Optim = "1.9"
Plots = "1.40.9"
ProgressMeter = "1.10.2"
Shapefile = "0.13.1"
Statistics = "1.10.0"
StatsBase = "0.34.3"
StatsPlots = "0.15.7"
UnPack = "1.0.2"
ZipFile = "0.10.1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
